//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPIGET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBVEHICULOSEntities1 : DbContext
    {
        public DBVEHICULOSEntities1()
            : base("name=DBVEHICULOSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<usrESTATU> usrESTATUS { get; set; }
        public virtual DbSet<VEHICULO> VEHICULOS { get; set; }
        public virtual DbSet<vhCONDICION> vhCONDICIONs { get; set; }
        public virtual DbSet<vhESTATU> vhESTATUS { get; set; }
    }
}
